# Generated by Django 3.0 on 2021-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45, null=True)),
                ('prenom', models.CharField(max_length=45, null=True)),
                ('telephone', models.IntegerField()),
                ('zone', models.CharField(max_length=50, null=True)),
                ('ouvrier', models.CharField(max_length=50)),
            ],
        ),
    ]
