# Generated by Django 3.0 on 2021-11-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='person.png', upload_to='profile_pics'),
        ),
    ]
