# Generated by Django 3.0 on 2022-01-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20211117_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
