# Generated by Django 3.0 on 2022-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20220304_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
