# Generated by Django 3.0 on 2022-03-04 21:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_auto_20220304_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='prenom',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
