# Generated by Django 3.0 on 2022-03-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_auto_20220304_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='prenom',
            field=models.TextField(),
        ),
    ]
