# Generated by Django 3.0 on 2022-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_auto_20220304_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='prenom',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
